dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.7"
install:
  - pip3 install -r install/requirements.txt
script:
  - python3 -m unittest discover -v -p test_*.py -s scripts/pygrill -t scripts
